name: Publish to Nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    - name: Build SDK
      run: |
        dotnet restore src\iovation.LaunchKey.Sdk.sln
        msbuild "src\iovation.LaunchKey.Sdk\iovation.LaunchKey.Sdk.csproj" /m /verbosity:minimal /p:GeneratePackageOnBuild=false
    - name: Run Tests
      run: dotnet test -f net462 src/iovation.LaunchKey.Sdk.Tests
    - name: Package SDK
      run: |
        dotnet pack "src\iovation.LaunchKey.Sdk\iovation.LaunchKey.Sdk.csproj" --configuration Release
    - name: Publish SDK
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -NonInteractive
