name: Test Dotnet SDK Versions

on: [pull_request, push]

jobs:
  run_on_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['4']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore src/iovation.LaunchKey.Sdk
    - name: Build SDK
      run: dotnet build src/iovation.LaunchKey.Sdk --no-restore
  
