name: Test Dotnet SDK Versions

on: [pull_request, push]

jobs:
  run_on_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: See where stuff is
      run: ls -la
  
